Stubs for missing implementations that use SDL
in order to get rid of this:

error: invalid new-expression of abstract class type ‘LLWindowSDL’
    fullscreen, clearBg, enable_vsync, use_gl, ignore_pixel_depth, fsaa_samples);
note: because the following virtual functions are pure within ‘LLWindowSDL’:
 class LLWindowSDL : public LLWindow
       ^~~~~~~~~~~
     virtual void* createSharedContext() = 0;
                   ^~~~~~~~~~~~~~~~~~~
     virtual void makeContextCurrent(void* context) = 0;
                  ^~~~~~~~~~~~~~~~~~
     virtual void destroySharedContext(void* context) = 0;
                  ^~~~~~~~~~~~~~~~~~~~
     virtual void toggleVSync(bool enable_vsync) = 0;
                  ^~~~~~~~~~~

The window has been relying on some, mostly GL context related, methods.
These methods are declared abstract, so for now they're implemented
using member functions that do nothing, return nothing.